---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: default
platforms:
  - name: "${MOLECULE_SCENARIO_NAME}-${MOLECULE_PARTITION_TYPE}-${MOLECULE_PARTITION_SIZE}g"
provisioner:
  name: ansible
  log: true
  env:
    ANSIBLE_VERBOSITY: ${MOLECULE_VERBOSITY:-0}
  config_options:
    defaults:
      interpreter_python: auto_silent
      callbacks_enabled: ansible.posix.profile_tasks
      callback_whitelist: profile_tasks, timer, yaml
  inventory:
    group_vars:
      all:
        libvirt_network: "nephelaiio-growfs"
        libvirt_platforms: "{{ molecule_yml.platforms }}"
        libvirt_address: "172.31.249.1/24"
        libvirt_path: "{{ molecule_project }}/libvirt/nephelaiio-ubuntu-installer"
        libvirt_privkey: "{{ libvirt_path }}/id_rsa"
        libvirt_guest_iso: "{{ alma_installer_target_dir }}/{{ alma_installer_target_filename }}"
        libvirt_guest_size: "{{ molecule_partition_size }}G"
        libvirt_guest_address: "{{ molecule_netaddr | ansible.utils.nthhost(2) }}"

        molecule_distro: "{{ lookup('env', 'MOLECULE_DISTRO') }}"
        molecule_installer_url: "{{ lookup('env', 'MOLECULE_ISO') }}"
        molecule_install_dir: "{{ lookup('env', 'MOLECULE_OUTPUT_DIR', default='/tmp/logs') }}"
        molecule_network: "{{ libvirt_address | ansible.utils.ipaddr('network') }}"
        molecule_netmask: "{{ libvirt_address | ansible.utils.ipaddr('netmask') }}"
        molecule_prefix: "{{ libvirt_address | ansible.utils.ipaddr('prefix') }}"
        molecule_netaddr: "{{ molecule_network }}/{{ molecule_prefix }}"
        molecule_project: "{{ lookup('ansible.builtin.env', 'MOLECULE_PROJECT_DIRECTORY') }}"
        molecule_partition_size: "{{ lookup('env', 'MOLECULE_PARTITION_SIZE') }}"
        molecule_partition_method: "{{ lookup('env', 'MOLECULE_PARTITION_METHOD') }}"
        molecule_partition_lvm: autopart
        molecule_partition_static: |
          part swap --size=4000
          part biosboot --fstype=biosboot --size=1
          part /boot --fstype=xfs --size=1000
          part / --fstype=xfs --grow --size=1

        alma_installer_image_url: "file:///{{ libvirt_path }}/{{ molecule_distro }}.iso"
        alma_installer_hostname: "{{ inventory_hostname }}"
        alma_installer_target_filename: "{{ inventory_hostname }}.iso"
        alma_installer_target_dir: "{{ libvirt_path }}"
        alma_installer_dhcp: false
        alma_installer_root_password: "{{ 'molecule' | password_hash('sha512') }}"
        alma_installer_username: molecule
        alma_installer_password: "{{ 'molecule' | password_hash('sha512') }}"
        alma_installer_address: "{{ libvirt_guest_address }}"
        alma_installer_netmask: "{{ libvirt_address | ansible.utils.ipaddr('netmask') }}"
        alma_installer_gateway: "{{ libvirt_address | ansible.utils.ipaddr('address') }}"
        alma_installer_nameservers: ["1.1.1.1", "8.8.8.8"]
        alma_installer_ks_partitioning: "{{ (molecule_partition_method == 'static') | ternary(molecule_partition_static, molecule_partition_lvm) }}"

verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - prepare
    - converge
    - verify
    - cleanup
