---
name: alma10
on:
  pull_request:
    branches:
      - master
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  SCENARIO: default
  DISTRO: almalinux10
  MIRROR: https://repo.almalinux.org/almalinux/10
  ISO: https://repo.almalinux.org/almalinux/10/isos/x86_64/AlmaLinux-10.1-x86_64-dvd.iso
  LOGDIR: "/tmp/logs"
  PART_SIZE: 30
jobs:
  lvm:
    name: lvm
    runs-on: libvirt
    env:
      PART_TYPE: lvm
    steps:
      - name: Run devbox tests
        uses: pokerops/ansible-utils@master
        with:
          run: |
            make requirements test \
              MOLECULE_SCENARIO=${{ env.SCENARIO }} \
              MOLECULE_LOGDIR=${{ env.LOGDIR }} \
              MOLECULE_DISTRO=${{ env.DISTRO }} \
              MOLECULE_ISO=${{ env.ISO }} \
              MOLECULE_PARTITION_METHOD=${{ env.PART_TYPE }} \
              MOLECULE_PARTITION_SIZE=${{ env.PART_SIZE }}

      - name: Upload install logs
        uses: actions/upload-artifact@v6
        with:
          name: install.${{ env.PART_METHOD }}.${{ env.SCENARIO }}.${{ env.DISTRO }}
          path: |
            ${{ env.LOGDIR }}/*.log
            ${{ env.LOGDIR }}/*.ppm
          if-no-files-found: ignore
        if: always()

  static:
    name: static
    runs-on: libvirt
    env:
      PART_TYPE: static
    steps:
      - name: Run devbox tests
        uses: pokerops/ansible-utils@master
        with:
          run: |
            make requirements test \
              MOLECULE_SCENARIO=${{ env.SCENARIO }} \
              MOLECULE_LOGDIR=${{ env.LOGDIR }} \
              MOLECULE_DISTRO=${{ env.DISTRO }} \
              MOLECULE_ISO=${{ env.ISO }} \
              MOLECULE_PARTITION_METHOD=${{ env.PART_TYPE }} \
              MOLECULE_PARTITION_SIZE=${{ env.PART_SIZE }}
              ALMA_BASEURL=${{ env.MIRROR }}

      - name: Upload install logs
        uses: actions/upload-artifact@v6
        with:
          name: install.${{ env.PART_METHOD }}.${{ env.SCENARIO }}.${{ env.DISTRO }}
          path: |
            ${{ env.LOGDIR }}/*.log
            ${{ env.LOGDIR }}/*.ppm
          if-no-files-found: ignore
        if: always()
