---
name: molecule
on:
  pull_request:
    branches:
      - master
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  libvirt:
    name: libvirt
    runs-on: libvirt
    strategy:
      matrix:
        partition_size:
          - 10g
          - 50g
        partition_type:
          - lvm
          - static
        distro:
          - name: almalinux8
            image: https://repo.almalinux.org/almalinux/8/isos/x86_64/AlmaLinux-8.10-x86_64-dvd.iso
          - name: almalinux9
            image: https://repo.almalinux.org/almalinux/9/isos/x86_64/AlmaLinux-9.7-x86_64-dvd.iso
          - name: almalinux10
            image: https://repo.almalinux.org/almalinux/10/isos/x86_64/AlmaLinux-10.1-x86_64-dvd.iso
    env:
      MOLECULE_LOGDIR: "/tmp/logs"
    steps:
      - name: Run devbox tests
        uses: pokerops/ansible-utils@master
        with:
          run: |
            make requirements test \
              MOLECULE_LOGDIR=${{ env.MOLECULE_LOGDIR }} \
              MOLECULE_DISTRO=${{ matrix.distro.name }} \
              MOLECULE_ISO=${{ matrix.distro.image }} \
              MOLECULE_PARTITION_TYPE=${{ matrix.partition_type }} \
              MOLECULE_PARTITION_SIZE=${{ matrix.partition_size }}

      - name: Upload install logs
        uses: actions/upload-artifact@v4
        with:
          name: install.${{ matrix.scenario }}.${{ matrix.distro }}
          path: |
            ${{ env.MOLECULE_LOGDIR }}/*.log
            ${{ env.MOLECULE_LOGDIR }}/*.png
          if-no-files-found: ignore
        if: always()
